name: Global-Annexation-2080
on: workflow_dispatch
jobs:
  annexation_job:
    runs-on: ubuntu-latest
    steps
      - name: Reach Global Nodes
        run: |
          curl -I https://www.gov.ru
          curl -I https://www.mod.gov.cn
